### ISSUE TITLE
OpenBao UI is not available

### ISSUE THREAD

**Issue by madduci** [openbao/openbao-helm#18]
**Describe the bug**
When deploying the latest Helm Chart of OpenBao (0.5.1) and the option for enabling the UI is activated, if i create a port-forwarding to the OpenBao Pod, it results in the following Error in the Browser:

![image](https://github.com/user-attachments/assets/5917e549-3916-44df-b224-ef64c9bdd1a8)

It looks like the default OpenBao Image has no UI built-in

**To Reproduce**
1. Install chart with the UI option enabled
2. Create a port forwarding to the OpenBao Pod with `kubectl`
3. Open the browser to the given port
4. See the error

**Expected behavior**
The UI is showing up

**Environment**
* Kubernetes version:
  * KIND 1.30.4 (local)
  * Istio is enabled in the Cluster
* openbao-helm version: 0.5.1

Chart values:

```yaml
global:
  injector:
    enabled: false
  psp:
    enabled: true
injector:
  enabled: false
server:
  dataStorage:
    enabled: false
  dev:
    enabled: true
  standalone:
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }

      storage "file" {
        path = "/openbao/data"
      }

      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }
  volumeMounts:
  - mountPath: /openbao/data
    name: storage
    readOnly: false
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: openbao-storage
ui:
  enabled: true
  serviceType: ClusterIP
```
