### ISSUE TITLE
`injector.agentInjector.registry` parameter is not respected

### ISSUE THREAD

**Issue by ipsavitsky** [openbao/openbao-helm#22]
**Describe the bug**
When setting the registry for the `agentImage` in the `values.yaml` file the chart tries to pull from `docker.io` because the registry is not set

**To Reproduce**
1. Set the value to the `injector.agentImage` in `values.yaml`  to a custom registry
1. Install chart
2. Set up a service that gets secrets injected into
3. See ImagePullBackOff on the injected container in the service pod

**Expected behavior**
The agent container installs and pulls secrets

**Environment**
* Kubernetes version: 1.31.1
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
* openbao-helm version: 0.6.0

Chart values:

```yaml
injector:
  agentImage:
    registry: <sensitive>
    repository: openbao
    tag: 2.0.2
  enabled: true
  image:
    registry: <sensitive>
    repository: vault-k8s
    tag: 1.4.2
  port: 8443
server:
  dataStorage:
    enabled: true
    storageClass: gp3
  extraInitContainers:
  - args:
    - cd /tmp && wget https://github.com/ilijamt/vault-plugin-secrets-gitlab/releases/download/v0.6.1/vault-plugin-secrets-gitlab_linux_x86_64.tar.gz
      -O gitlab.tar.gz && tar -xf gitlab.tar.gz && mv vault-plugin-secrets-gitlab_v0.6.1
      /plugins/gitlab_v0.6.1 && chmod +x /plugins/gitlab_v0.6.1
    command:
    - sh
    - -c
    image: alpine
    name: gitlab
    volumeMounts:
    - mountPath: /plugins
      name: plugins
  image:
    registry: <sensitive>
    repository: openbao
    tag: 2.0.2
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: default-acme
    enabled: true
    hosts:
    <sensitive>
  livenessProbe:
    enabled: true
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  serviceAccount:
    createSecret: true
  standalone:
    config: |
      ui = false
      plugin_directory = "/plugins"
      log_level = "info"

      listener "tcp" {
        tls_disable = true
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/openbao/data"
      }

      seal "shamir" {}
    enabled: true
  volumeMounts:
  - mountPath: /plugins
    name: plugins
    readOnly: true
  volumes:
  - emptyDir: {}
    name: plugins

```

**Additional context**
It appears that the problem is in the `AGENT_INJECT_VAULT_IMAGE` envvar set for agent injector, which does not mention the registry parameter at all
https://github.com/openbao/openbao-helm/blob/72b4014e67750a31a08056c827cbc982575afba7/charts/openbao/templates/injector-deployment.yaml#L71-L72
should be
```yaml
- name: AGENT_INJECT_VAULT_IMAGE
   value: "{{.Values.injector.agentImage.registry}}/{{ .Values.injector.agentImage.repository }}:{{ .Values.injector.agentImage.tag }}"
```
