### ISSUE TITLE
Change the order of extraEnvxironmentVars and extraSecretEnvironmentVars evaluation in server-statefulset.yaml to provide flexibility

### ISSUE THREAD

**Issue by vijaySamanuri** [openbao/openbao-helm#37]
Currently, in OpenBao's Helm chart, `extraEnvironmentVars` are evaluated before `extraSecretEnvironmentVars` as seen in the StatefulSet template:

https://github.com/openbao/openbao-helm/blob/main/charts/openbao/templates/server-statefulset.yaml#L141-L142

```
           {{- include "openbao.extraEnvironmentVars" .Values.server | nindent 12 }}
           {{- include "openbao.extraSecretEnvironmentVars" .Values.server | nindent 12 }}
```

However, it would be better to include `extraSecretEnvironmentVars` first, allowing `extraEnvironmentVars` to reference them for variable substitution.

##### Example Problem:

If the following configuration is defined in `values.yaml` `openbao.server` section:

```
extraSecretEnvironmentVars:
- envName: PG_OB_USERNAME
  secretName: openbao-pg-secret
  secretKey: username
- envName: PG_OB_PASSWORD
  secretName: openbao-pg-secret
  secretKey: password
- envName: PG_OB_DATABASE
  secretName: openbao-pg-secret
  secretKey: dbname

extraEnvironmentVars:
  BAO_PG_CONNECTION_URL: "postgresql://$(PG_OB_USERNAME):$(PG_OB_PASSWORD)@postgres.$(BAO_K8S_NAMESPACE).svc.cluster.local:5432/$(PG_OB_DATABASE)?sslmode=disable"
```
Since `extraEnvironmentVars` are evaluated before `extraSecretEnvironmentVars`, variable substitution does not occur for `BAO_PG_CONNECTION_URL`.

### Suggested Improvement:

Reversing the order of inclusion in the StatefulSet template:

```
          {{- include "openbao.extraSecretEnvironmentVars" .Values.server | nindent 12 }}
          {{- include "openbao.extraEnvironmentVars" .Values.server | nindent 12 }}
```
This change provides greater flexibility, allowing `extraEnvironmentVars` to reference environment variables derived from secrets.

for my use-case i know we can directly have postgresql connection-string in the secret instead to make it work. 

However, modifying the order of evaluation offers a more general and flexible approach, benefiting other use cases as well.
