### ISSUE TITLE
Missing UI binary

### ISSUE THREAD

**Issue by MartijnZuijderduijn** [openbao/openbao-helm#47]
**Describe the bug**
With the latest version of the helm chart 0.10.1, version 2.2.0 of the openbao is used. According to the release notes on the openbao repo itself this is the first version that contains the UI component. However when I try to access the UI I still get the "OpenBao UI is not available in this binary." page.

**To Reproduce**
1. Install chart in openbao namespace
2. kubectl port-forward -n openbao services/openbao-ui 1337:8200
3. open localhost:1337

**Expected behavior**
Version 2.2.0 should contain ui component as advertised. Can we get a version of the openbao image that contains the UI?

**Comment by MartijnZuijderduijn** [comment]
My apologies, I was doing a `helm update --install` command on an existing release not a new release.

my config is 
```yml
global:
  openshift: true

injector:
  enabled: false

ui:
  enabled: true

csi:
  enabled: true
  daemonSet:
    securityContext:
      container:
        privileged: true
        capabilities:
          drop:
          - ALL
  priorityClassName: system-node-critical

  agent:
    enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 256Mi

server:
  standalone:
    enabled: false

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

  extraSecretEnvironmentVars:
  - envName: VAULT_TOKEN
    secretName: openbao-vault-token
    secretKey: VAULT_TOKEN

  ha:
    enabled: true
    replicas: 3

    raft:
      # Enables Raft integrated storage
      enabled: true
      # Set the Node Raft ID to the name of the pod
      setNodeId: true

      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        seal "transit" {
          address = "REDACTED:8200"
          disable_renewal = "false"
          mount_path = "transit/"
          tls_skip_verify = "true"
        }
        storage "raft" {
          path = "/openbao/data"
          retry_join {
            auto_join = "provider=k8s label_selector=\"app.kubernetes.io/name=openbao,component=server\" namespace=\"openbao\" "
            auto_join_scheme = "http"
          }
        }

        service_registration "kubernetes" {}

        # Example configuration for enabling Prometheus metrics.
        # If you are using Prometheus Operator you can enable a ServiceMonitor resource below.
        # You may wish to enable unauthenticated metrics in the listener block above.
        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }

```
